name: pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests with Maven
        run: ./mvnw verify

      - name: Check Test Status
        run: |
          if [ ${{ job.status }} != 'success' ]; then
            echo "Tests failed. Exiting..."
            exit 1
          fi